[package]
name = "bgutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
json = "0.12.4"
notify-rust = "4.9.0"
reqwest = "0.11.22"
url = "2.4.1"
